name: msba_website
channels:
  - conda-forge
dependencies:
  - blas=*=openblas
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - matplotlib-base
  - numpy
  - pandas
  - pip
  - polars
  - python=3.14
  - r-base=4.5
  - r-crayon
  - r-dplyr
  - r-ggplot2
  - r-rmarkdown
  - r-tibble
  - r-tidyr
  - scipy
  - statsmodels
