---
title: Introduction to Python
---

## Goals

1. Understand that programs are run in some context: file system, operating system, hardware, and so on.
2. Develop a mental model for programming.
3. Introduce basic syntax and its semantics: variables, literals, functions, and assignment.



## What is a programming language?

- A system of notation by which a programmer communicates a program to a computer.
- A program is a sequence of instructions that computes something; there are inputs and outputs.
- In contrast, a machine language is a formal system by which a computer understands and executes a program.
- The term computer language is a broader term that includes programming, machine, markup, and other languages used in computing.



## Syntax and Semantics

The Python runtime can only understand your instructions through the rules of the language. The language is composed of:

**Syntax**: What you can say and how you represent ideas.
    - The syntax in a language defines rules. Break them and Julia will complain.
    - Might feel arbitrary… because it is!
    - These are deliberate design decisions that make trade-offs between competing requirements.
    - Tools built into integrated development environments (IDE) such as VSCode can often help catch these mistakes.
**Semantics**: The intended meaning of symbols and rules.
    - Requires lots of exposure and practice to master.
    - Julia’s syntax is quite clean at the surface level, but implications at the semantics level run deep.
    - IDE tools are less likely to catch semantic errors, which often surface as unexpected behavior or incorrect results when your code runs.

We will focus heavily on syntax in the beginning to learn how we can represent data and concepts within the language.



## Basic Python Syntax

### Literals

A literal is a symbol (or collection of symbols) used to denote a particular value. The symbols following symbols are all literals for specific types of data.

```{python}
1 #int
```

```{python}
3.14 # float
```

```{python}
'STAT 206' # str
```



### Variables

A variable is an identifier used to reference a particular value.

```{python}
sales_sept = 10
```

```{python}
sales_oct = 13
```

```{python}
sales_sept + sales_oct
```



### Assignment

Creating variables requires assignment with `=`.
In Python, you can bind a variable to

- a literal,
- another variable,
- a function, or
- just about any object in the language.

The specific meaning of `=` is determined by context but it is *always* binding a value to a symbol.
What changes is the *namespace* or *scope* in which that symbol is defined.



### Functions and Operators

If variables and literals are nouns in a programming language, then functions are the verbs. Python comes with many built-in functions, though foundational mathematical operations are split between built-ins (like `sum()`, `abs()`, and `pow()`) and the standard math module (like `math.exp()` and `math.log()`).

Operators such as `+` are linked to special functions called *methods* that we will cover much later in the course.
It is enough to understand that `+` is just a function that supports infix notation.

```{python}
1 + 3 # infix notation
```

```{python}
import operator

operator.add(1, 3) # this is what `+` actually is in the language
```



### Special Constructors

Virtually every object in Python has a **constructor** to create an object from given inputs.
As a matter of convention:

- these functions always start with an uppercase letter, and
- have names aligned to the type of object they construct.

```{python}
int("3")
```

```{python}
str(206)
```

You will encounter many objects and their constructors as you progress through this course.
